### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by DazWorrall** [nilebox/kanarini#11]
Apologies if I missed it but I can't see what license this code is made available under.

**Comment by nilebox** [comment]
hi @DazWorrall, apologies, I have just added Apache License 2.0

**Comment by DazWorrall** [comment]
Thanks @nilebox! While I have your attention, can I ask about the status of your prohect: Is it a proof of concept, or being used in production for example? Are you still developing/maintaining it?

Thanks very much for sharing it regardless.

**Comment by nilebox** [comment]
@DazWorrall this is my personal project that has been implemented as a proof of concept for my KubeCon talk https://kccna18.sched.com/event/GrUI/custom-deployment-strategies-for-kubernetes-nail-islamov-atlassian, the recording is available at https://youtu.be/nh-yy3BWbjg

I wouldn't consider it production ready mostly because there are no tests except the manual walkthrough :(

It has been in active development till last December, but I didn't have time to work on it recently.
I'm happy to discuss issues and accept pull requests if you find any issues with this project.

**Comment by nilebox** [comment]
I am also available on Kubernetes Slack as @nilebox, feel free to ping me there if you have any questions.

**Comment by DazWorrall** [comment]
Thanks for that context @nilebox, much appreciated.
